### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by wondering639** [romansp/skpm-typescript#6]
I just started with Sketch plugin development and wanted to use TypeScript instead of directly using JavaScript. I therefore used this template. But I don't understand how to use it - where can I find the types that are available in this TypeScript template? For example I would expect something like SketchDocument as interface or class. There is MSDocument, but this contains only showMessage.
Could you give some starting support? Thanks and thanks for this TypeScript plugin :-)

Hint: I am using Visual Studio Code. Would be interested in auto-completion etc.

**Comment by romansp** [comment]
Hi @wondering639! Unfortunately there are no typings provided by this template. It only scaffolds initial build environment so you can use TS to write Sketch plugins. To use this template successfully you will have to add required typings manually into `sketch.d.ts` file.

I tried to implement automated definition generation previously here https://github.com/romansp/sketch-headers-typescript based on the work from this repo https://github.com/skpm/sketch-headers/issues. I don't work on that anymore, but i guess it's still doable.

**Comment by wondering639** [comment]
@romansp Sad to hear that, but thanks for the clarification :-) Guess for my beginner project I will stay with pure JavaScript, doing all the TypeScript stuff manually is currently too much for me.
